language: python

install: skip

script:
  - which hg
  - pip freeze
  - pip freeze | grep -i mercu

matrix:
  include:
    - sudo: required
      dist: precise
      env: DIST=precise STACK=GCE
    - sudo: false
      dist: trusty
      env: DIST=trusty STACK=EC2
    - sudo: required
      dist: trusty
      env: DIST=trusty STACK=GCE
    - sudo: false
      dist: trusty
      group: edge
      env: DIST=trusty STACK=EC2 GROUP=edge
    - sudo: required
      dist: trusty
      group: edge
      env: DIST=trusty STACK=GCE GROUP=edge
#     - os: osx

notifications:
  email: false
