language: objective-c
script:
          - df -h / 
          - uname -a
          - xcodebuild -version
          - swift -version

matrix:
  include:
  - os: osx
  osx_image: xcode7.3
  - os: osx
  osx_image: xcode8
  - os: osx
  osx_image: xcode8.1
  - os: osx
  osx_image: xcode8.2
  - os: osx
  osx_image: xcode8.3
  - os: osx
  osx_image: xcode9
  - os: osx
  osx_image: xcode9.1

