language: objective-c

osx_image: xcode9.4

script:
  - uname -a
  - df -h /
  - xcodebuild -version
  - brew list --versions
  - brew cask list --versions
  - rvm list
  - motion --version
  - pod --version
  - swift -version
  - xcrun simctl list
  - xcrun simctl list pairs
  - echo "xcode-9.4 prod image output complete"
