language: android

android:
  components:
    - tools
    - platform-tools
    - tools
    
    - android-25
    
    - build-tools-25.0.2
    - extra
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

jdk: oraclejdk8

install: skip

script:
  - sdkmanager --list
