language: node_js

install: skip

script:
  - yarn version


matrix:
  include:

    - sudo: required
      dist: trusty
      language: __garnet__
      group: edge
      env: GCE GROUP=edge GARNET
    - sudo: required
      dist: trusty
      language: __garnet__
      group: stable
      env:  GCE GROUP=STABLE GARNET
    - sudo: required
      dist: trusty
      language: __sugilite__
      group: edge
      env: GCE GROUP=edge SUGILITE
    - sudo: required
      dist: trusty
      language: __sugilite__
      group: stable
      env:  GCE GROUP=STABLE SUGILITE
    - sudo: false
      dist: trusty
      language: node_js
      env: DIST=trusty STACK=EC2
    - sudo: false
      dist: precise
      env: DIST=precise STACK=EC2
      language: node_js
    - sudo: required
      dist: precise
      env: DIST=precise STACK=GCE
      language: node_js

notifications:
  email: false
