sudo: required
language: android

android:
  components:
    - tools
    - platform-tools
    - tools
    - android-25
    - build-tools-26.0.2
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-25

jdk: oraclejdk8

install: skip

script:
  - sdkmanager --list
  - gradle --version
