

script:
  - locate bin/php
  - pyenv --version
  - sudo find / -type f -executable -iname 'python*' -exec file -i '{}' \; | awk -F: '/x-executable; charset=binary/ {print $1}' | xargs readlink -f | sort -u | xargs -I % sh -c 'echo -n "%: "; % -V'
  - pypy --version
  - node --version
  - node --v8-options
  - node -p process.versions.v8
  - firefox -version
  

matrix:
  include:

    - sudo: required
      language: __amethyst__
      group: dev
      env: GCE GROUP=dev AMETHYST
    - sudo: required
      language: __amethyst__
      group: stable
      env: GCE GROUP=stable AMETHYST
    - sudo: required
      language: __connie__
      group: dev
      env: GCE GROUP=dev CONNIE
    - sudo: required
      language: __connie__
      group: stable
      env: GCE GROUP=stable CONNIE
    - sudo: required
      language: __garnet__
      group: dev
      env: GCE GROUP=dev GARNET
    - sudo: required
      language: __garnet__
      group: stable
      env:  GCE GROUP=STABLE GARNET
    - sudo: required
      language: __sugilite__
      group: dev
      env: GCE GROUP=dev SUGILITE
    - sudo: required
      language: __sugilite__
      group: stable
      env:  GCE GROUP=STABLE SUGILITE
    - sudo: false
      language: php


notifications:
  email: false
