language: python

install: skip

script:
  - which hg
  - pip freeze
  - pip freeze | grep -i mercurial
  - dpkg -L mercurial 

matrix:
  include:
    - sudo: required
      dist: trusty
      language: __connie__
      group: dev
      env:  connie dev image GCE
    - sudo: false
      dist: trusty
      language: __connie__
      env: connie stable image EC2

notifications:
  email: false
