
sudo: false
dist: trusty

matrix:
    include:
        - env: image=garnet
          language: __garnet__
        - env: image=amethyst
          language: __amethyst__

services:
    - mysql
install: true
script:
    - mysql -e 'SELECT * from mysql.user\G;'
    - mysql -e 'DESC mysql.user\G;'
